### ISSUE TITLE
nice source

### ISSUE THREAD

**Issue by dschaf** [Android1337/Basic-Fortnite-Cheat-Source-Internal#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2975	'Css': invalid template argument for 'jm::detail::tstring_', expected compile-time constant expression	AndroidUpdated	C:\Users\Dakota\Desktop\AndroidsSource\Basic-Fortnite-Cheat-Source-Internal-main\AndroidUpdated\imgui\imgui_xorstr.h	229	

when i replace with a different xorstr it creates more errors other than the error on compile looks like a clean base.

**Comment by Android1337** [comment]
Figure it out yourself that source is not for pasters
