### ISSUE TITLE
faggot

### ISSUE THREAD

**Issue by dschaf** [Android1337/Basic-Fortnite-Cheat-Source-Internal#2]

**Comment by Android1337** [comment]
No? And what base is it then faggot?

**Comment by dschaf** [comment]
it was posted a while ago and minhook base and also hopesarr posted the base theres mutiple post

**Comment by Android1337** [comment]
Ehm as I see no-one in this season had publish a working source internal with esp so...

**Comment by Android1337** [comment]
Where are thoosd multiple working posts?

**Comment by dschaf** [comment]
and..... my internal is fully working lmao and im not even talking about that

**Comment by Android1337** [comment]
Yes yes its fully working cuz u pasted that lmao
